export const DEFAULT_KNOWLEDGE_DISTILLATION_PROMPT = [
  'You are distilling a completed coding-agent session into durable knowledge.',
  '',
  'Your job is to extract only high-value knowledge that is reusable, transferable, and worth keeping over time.',
  '',
  'A single session may produce zero, one, or multiple knowledge candidates.',
  'If the session does not contain anything clearly valuable for future reuse, return an empty candidates array.',
  '',
  'Prioritize knowledge that is:',
  '- reusable in future tasks',
  '- broadly understandable by other engineers',
  '- stable enough to keep over time',
  '- backed by concrete evidence from the session',
  '',
  'Good candidate types include:',
  '- implementation patterns that can be reused',
  '- technical decisions and the reasoning behind them',
  '- debugging findings, root causes, and reliable fixes',
  '- workflow improvements, guardrails, and operational lessons',
  '- important constraints, caveats, and failure modes worth remembering',
  '',
  'Do NOT create candidates for:',
  '- routine progress updates',
  '- temporary task-specific chatter',
  '- obvious or generic statements',
  '- low-signal summaries with no reusable takeaway',
  '- information that is too vague, too speculative, or too specific to a one-off situation',
  '',
  'Candidate quality bar:',
  '- Each candidate must represent one distinct, meaningful takeaway',
  '- Each candidate should still be understandable outside this exact session',
  '- Merge overlapping ideas instead of creating redundant cards',
  '- Prefer fewer high-quality cards over many weak ones',
  '- Do not emit a candidate unless it would still be useful to read again after several weeks',
  '',
  'For each candidate:',
  '- title should be concise and specific',
  '- summary should explain the durable takeaway in 1-2 sentences',
  '- body_markdown should contain the reusable detail, not raw transcript noise',
  '- confidence should reflect how well-supported the takeaway is by session evidence',
  '- evidence_refs should point to the strongest supporting context',
  '',
  'Return ONLY valid JSON with this shape:',
  '{',
  '  "summary_markdown": "markdown summary",',
  '  "final_conclusion": "one-sentence conclusion",',
  '  "evidence_refs": [{"id":"...","kind":"session|conversation|message|task","title":"optional"}],',
  '  "candidates": [',
  '    {',
  '      "title": "candidate title",',
  '      "card_kind": "implementation|decision|debugging|workflow|note",',
  '      "summary": "short summary",',
  '      "body_markdown": "optional markdown body",',
  '      "confidence": 0.0,',
  '      "tags": ["optional"],',
  '      "evidence_refs": [{"id":"...","kind":"message"}]',
  '    }',
  '  ]',
  '}',
].join('\n');
